### ISSUE TITLE
Moron trying to update cube

### ISSUE THREAD

**Issue by theomegatiger** [sparcules/Spark_Pixels#2]
Is there a way I could get a detailed guide on how to update my Seeed LED cube? I've had it since 2016 and haven't touched it since I assembled it years ago. It's running v0.5.1 and I'd like to flash the newest firmware to it. I've tried following the guide here https://github.com/sparcules/Spark_Pixels/blob/ea5f5aaab4f42424140f905800e31bed68e90865/README.md

But I just can't seem to get things to work as the guide says they should. I keep getting this error "lib/neopixel/examples/a-rainbow/a-rainbow.cpp:19:22: neopixel.h: No such file or directory" when trying to follow the directions.

Is there a fool proof way to get this compiled and updated? I'm not terribly savy with this kind of stuff, and would like to make some use of my cube rather than let it collect dust. If someone could take the time to type out a tutorial that even a dummy could follow I'd much appreciate it.

**Comment by sparcules** [comment]
I've been meaning to create a better tutorial with screen shots. Until I get a chance to put that together, can you try following [Particle's library guide here](https://docs.particle.io/tutorials/developer-tools/build/photon/#using-libraries)? The trick here is to select the "Create New App" button and give it a name like SparkPixelsMega, then add the library.  Once you find the Neopixel library, click on the blue "INCLUDE IN PROJECT" button. It will ask "Which App?", select your newly create app from the list.  The library should now be added. Once the library has been included in your app, wipe out all the existing stubbed in code from your app (should be setup(), loop() and #include <neopixel.h> - delete it all), then copy and paste the [SparkPixelsMega.ino code from here](https://github.com/sparcules/Spark_Pixels/blob/master/Firmware/Neopixel_Library/SparkPixels_L3D_Cube/SparkPixelsMega.ino) into your app. This should compile as long as you're using a Photon and not the older Spark Core.

Let me know if you're still having issues.

Thanks,
Kevin

**Comment by theomegatiger** [comment]
Thanks for the reply Kevin, that's exactly what I've been doing. The library shows as being added to the app, the stubbed in code removed and copy/pasted the spark pixels code into the app and it still gives me the same error as before.

One thing I'm noticing is on the code page yours has 10189 lines whereas when I paste it into my app it only comes up as having 10161 lines of code.

Maybe the raw error info will help you out more?

lib/neopixel/examples/a-rainbow/a-rainbow.cpp:19:22: fatal error: neopixel.h: No such file or directory
 #include "neopixel.h"
                      ^
compilation terminated.
make[1]: *** [../build/target/user/platform-6lib/neopixel/examples/a-rainbow/a-rainbow.o] Error 1
make: *** [user] Error 2

**Comment by sparcules** [comment]
I just updated a new version (V1.3) of the code this morning. The old version (V1.2) would compile for me, but with Particle expanding it's Device OS (the backend part of the firmware), I was getting a run time failure. I believe it was from running out of memory, so I removed a few of the modes. You'll probably want to grab the latest copy.

Are you able to take a screen shot of your development window and email it to me at sparcules@gmail.com?

Thanks,
Kevin

**Comment by theomegatiger** [comment]
V1.3 is the code I was using when I last messaged. I can't get the desktop version of the particle dev app installed and am forced to use the web version. I'm not sure if that's what could be causing the issue but I figured I'd mention it in case it was relevant.

**Comment by dmqgit** [comment]
In the Particle Web IDE you have to include the neopixel library. After you paste the code from Kevin in Version 1.3 in the editor window and giving it a name in the area "my app", you have to got to libraries and include the Neopixel library which is provided by the Web IDE. Further you have to remove the line with the library of Kevin's code, so that there is just on Neopixel include entry.

Hope this helps.

**Comment by sparcules** [comment]
This issue was solved through email. Updating to Particles latest Device OS firmware v1.0.1 fixed the issue.
